# Generated by Django 5.1.7 on 2025-04-16 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="timestamp",
        ),
    ]
