# Generated by Django 5.1.7 on 2025-04-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subrabble",
            old_name="descriptive_name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subrabble",
            name="identifier",
            field=models.TextField(null=True, unique=True),
        ),
    ]
