# Generated by Django 5.1.7 on 2025-04-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0004_rename_descriptive_name_subrabble_title_post_likes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments",
            field=models.IntegerField(default=0),
        ),
    ]
