# Generated by Django 5.1.7 on 2025-04-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0005_post_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subrabble",
            name="identifier",
            field=models.TextField(unique=True),
        ),
    ]
