# Generated by Django 5.1.7 on 2025-04-24 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0006_alter_subrabble_identifier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="comments",
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent_comment_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="rabble.comment",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="rabble.post",
            ),
        ),
        migrations.RemoveField(
            model_name="community",
            name="admin_id",
        ),
        migrations.RemoveField(
            model_name="community",
            name="user_id",
        ),
        migrations.AlterField(
            model_name="conversation",
            name="account_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="community_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="rabble.community",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="conversation_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="rabble.conversation",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="account_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="subRabble_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="rabble.subrabble",
            ),
        ),
        migrations.AlterField(
            model_name="subrabble",
            name="community_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rubRabbles",
                to="rabble.community",
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="admin_id",
            field=models.ManyToManyField(
                related_name="community_admins", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="user_id",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="community_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
