# Generated by Django 5.1.7 on 2025-04-30 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0009_commentlike_postlike_delete_like"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subrabble",
            old_name="annonymous",
            new_name="anonymous",
        ),
    ]
